name: BuildOffManager
main: me.flexo.buildoffmanager.BuildOffManager
version: 2.1
website: http://www.polygoncraft.net
description: Manages Build Offs
author: Flexo013
depend: [WorldGuard,WorldEdit]
commands:
  join:
    description: Join the current Build Off.
    usage: §cThe correct format is /join
    permission: buildoffmanager.default
  leave:
    description: Leave the current Build Off.
    usage: §cThe correct format is /leave
    permission: buildoffmanager.default
  forceleave:
    description: Forces a player to leave the current Build Off.
    usage: §cThe correct format is /forceleave [plot_owner]
    permission: buildoffmanager.op
  tpplot:
    description: Teleport the player the plot of [plot_owner].
    usage: §cThe correct format is /tpplot [plot_owner]
    permission: buildoffmanager.default
  theme:
    description: Displays the theme of the current Build Off.
    usage: §cThe correct format is /theme
    permission: buildoffmanager.default
  settheme:
    description: Changes the theme of the Build Off to [new_theme].
    usage: §cThe correct format is /settheme [new_theme]
    permission: buildoffmanager.op
  openbuildoff:
    description: Open a new Build Off.
    usage: §cThe correct format is /openbuildoff
    permission: buildoffmanager.op
  openbo:
    description: Open a new Build Off.
    usage: §cThe correct format is /openbo
    permission: buildoffmanager.op
  startbuildoff:
    description: Start a new Build Off.
    usage: §cThe correct format is /startbuildoff
    permission: buildoffmanager.op
  startbo:
    description: Start a new Build Off.
    usage: §cThe correct format is /startbo
    permission: buildoffmanager.op
  endbuildoff:
    description: End the current Build Off.
    usage: §cThe correct format is /endbuildoff
    permission: buildoffmanager.op
  endbo:
    description: End the current Build Off.
    usage: §cThe correct format is /endbo
    permission: buildoffmanager.op
  resetbuildoff:
    description: Resets the Build Off area and contestant list.
    usage: §cThe correct format is /resetbuildoff
    permission: buildoffmanager.op
  resetbo:
    description: Resets the Build Off area and contestant list.
    usage: §cThe correct format is /resetbo
    permission: buildoffmanager.op
  resetplot:
    description: Regenerates one specific plot.
    usage: §cThe correct format is /resetplot [plot_number]
    permission: buildoffmanager.op
  listplayers:
    description: List all players online.
    usage: §cThe correct format is /listplayers
    permission: buildoffmanager.listplayers
  bominit:
    description: Initializes Build Off plots.
    usage: §cThe correct format is /bominit
    permission: buildoffmanager.op
  reloadbom:
    description: Reloads the BuildOffManager config.
    usage: §cThe correct format is /reloadbom
    permission: buildoffmanager.op
  bohelp:
    description: Displays BuildOffManager basic help.
    usage: §cThe correct format is /bohelp
    permission: buildoffmanager.default